name:                bitcoin
version:             0.1.0.0
github:              "githubuser/bitcoin"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bitcoin#readme>

dependencies:
- base >= 4.7 && < 5
- array
- base58-bytestring
- binary
- bytestring
- cryptonite
- memory
- murmur3
- mwc-random
- mtl
- network
- time
- vector-sized 

library:
  source-dirs: src

executables:
  bitcoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitcoin
    - binary
    - bytestring
    - containers
    - mwc-random
    - network
    - vector-sized
    - directory
    - memory
    - cryptonite
    - stm
    - base58-bytestring
    - secp256k1 # -haskell
tests:
  bitcoin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitcoin
